### PR TITLE
Add Norman Layout

### PR DESCRIPTION
**Pull request by bsteindorf**
I know some people who use the norman layout, so may it would be nice to add it to the firmware.

### CODE REVIEW

**Comment by DreymaR** [comment]
Why don't they use Colemak-DH instead? Seems like a much much better layout
(fixes access to D and H, while maintaining the good stats of Colemak with
respect to same-finger etc etc). So if you want to support Norman you
should certainly support Colemak-DH!

There are two variants of it, DbgHk (DreymaR's) and DvbgHm (Stevep99's),
both described at the Colemak forums.

**Comment by bsteindorf** [comment]
Norman was the easiest to remember/learn layout to me, took about 1h to remember all keys.

But i never noticed that there are Colemak mods, i look into it now.

**Comment by DreymaR** [comment]
Here's my take on it:

http://forum.colemak.com/viewtopic.php?pid=16151#p16151

**Comment by technomancy** [comment]
I welcome contributions of any layouts people may be interested in; thanks for submitting this.

**Pull request merged**
