### PR TITLE
Try out a fully "Lorent" world on the Atreus

### PR DESCRIPTION
**Pull request by gerbercj**
This is a potential alternative for #46, which should also address #49 and #48.

This change does a few things:
- Make fn+Shift momentarily switch to layer 2
- Move reset to the N on layer 2
- Make the old reset and Enter again on layer 2
- Swap the arrows for the FN keys on layer 2 (left/right hand)
- To use shift on layer 2 you must jump, rather than use momentary

I like that this is unobtrusive for other users of the firmware, and gives a path for still using shift on layer 2. I don't like that I needed to make an extra layer that was nearly identical to layer 2.

### CODE REVIEW

**Comment by gerbercj** [comment]
Thinking about this further, it may be interesting to treat `layer_to_momentary` like a bitmask similar to `keyboard_modifier_keys`. This would allow for permutations of modifier keys. The use case that comes to mind is a custom version of shift, combined with a function key. Without the function key, the "shifted" layer could contain characters that are not the traditional value expected. More specifically, `shift`+`[` could map to `]`, `fn`+`[` could map to `{`, and `shift`+`fn`+`[` could map to `}`.

Thoughts? I'm not going to put any time into this change unless there is actual value...

**Comment by lorentrogers** [comment]
So cool! I feel honored to have a file named after me.

I did try loading it up, but I couldn't actually get it into a usable state... The layer 0 keys would work until I tried shifting. Then it would just print out random characters or nothing after that. Had to hard-reset to get back to default firmware...

**Comment by technomancy** [comment]
The changes described sound good, but for this to be truly unobtrusive I think it would need to copy the stuff from `layout_common.h` into `lorent.h` because otherwise it would mess up existing layouts. For instance, most layouts don't have 3 layers, so the `layer_jump` function would have undefined behavior.

**Comment by technomancy** [comment]
Also it would be great if each layout could have a description in a comment at the top so people know what it's for--what changes it makes from the default, why you might prefer it.

**Comment by gerbercj** [comment]
All great feedback... thanks! I'll try to carve some time out tonight to do some debugging and clean up the code.

**Comment by gerbercj** [comment]
This is working well for me locally. Keep in mind that you need to copy `lorent.h` to `layout.h` before you load it on your keyboard.

**Comment by technomancy** [comment]
Closing this out as QMK, Kaleidoscope, and Menelaus are all better choices now than this codebase.

**Pull request closed without merging**
